/**
 * This is the main js file for the entire application.
 * The library generated by webpack is called Client
 * The application is initiated by calling octo.init()
*/


/**
 * octo short for octopus is in charge of connecting the view to the 
 * model. In particular will handle all the interaction between 
 * DOM elements and backend API.
*/
const octo = {
    init: () => {
        view.init()
    }
}

/**
 * The view object contains all the functions  
 * 
*/
const view = {
    init: () => {
        view.eventHandlers();
    },

    updateDOM: (data) => {
        console.log(data)
    },

    eventHandlers: () => {
        const textForm = document.querySelector('#textForm')
        textForm.addEventListener('submit', (event) => {
            event.preventDefault();
            Client.handleSubmit('combined', textForm)
                .then((data) => {
                    view.updateDOM(data);
                })
        })
    }
}


// Iinitiate the application
export { octo }